# Default CI

name: project-euler-2-29-ci

on: [push, pull_request]


jobs:
  static-dynamic-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip' # caching pip dependencies
      - name: Setup Python Dependencies
        run: pip install -r requirements.txt
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'  # or: 'x64', 'x86', 'arm32', 'arm64' (or 'aarch64')
          distribution: 'full' # or: 'minimal' (but you probably don't want 'minimal', see note at the bottom of this doc)
          variant: 'CS'        # or: 'BC' for Racket Before Chez
          version: '8.5'
      - name: Setup Racket Formatter - racket-fmt
        run: raco pkg install --deps search-auto fmt
      - name: Setup Racket Linter - racket-review
        run: raco pkg install --deps search-auto review
      # - name: Setup Racket Resyntax
      #   run: sudo raco pkg install --deps search-auto --installation resyntax # I know this is bad practice
      - name: Caching Racket Dependencies
        uses: actions/cache@v3
        with:
          path: |
            /usr/share/racket/pkgs
            ~/.local/share/racket/8.5/pkgs
          key: ${{ runner.os }}-racket-${{ hashFiles('/share/pkgs/pkgs.rktd') }}
          restore-keys: ${{ runner.os }}-racket
      - name: Linting Python Scripts
        run: pylint scripts/py/* tests/py/*
      - name: Check Racket Scripts Formatting
        run: diff -u <(cat scripts/rkt/*.rkt tests/rkt/*.rkt) <(raco fmt scripts/rkt/*.rkt tests/rkt/*.rkt)
      - name: Linting Racket Scripts
        run: find scripts/rkt/ tests/rkt/ -type f -name *.rkt -print0 | xargs -0 -n1 raco review
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:scripts/py" >> $GITHUB_ENV
      - name: Running tests with PyTest
        run: pytest
      - name: Running tests with RackUnit
        run: find tests/rkt/ -type f -name *-test.rkt -print0 | xargs -0 -n1 racket

