# Default CI

name: project-euler-2-29-ci

on: [push, pull_request]


jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pip' # caching pip dependencies
      - name: Setup Python Dependencies
        run: pip install -r requirements.txt
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'  # or: 'x64', 'x86', 'arm32', 'arm64' (or 'aarch64')
          distribution: 'full' # or: 'minimal' (but you probably don't want 'minimal', see note at the bottom of this doc)
          variant: 'CS'        # or: 'BC' for Racket Before Chez
          version: '8.5'
      - name: Setup Racket Linter - racket-review
        run: raco pkg install review
      - name: Setup Racket Resyntax
        run: sudo raco pkg install --deps search-auto --installation resyntax # I know this is bad practice
      - name: Caching Racket Dependencies
        uses: actions/cache@v3
        with:
          path: |
            /share/pkgs
            ~/.local/share/racket/8.5/pkgs
          key: ${{ runner.os }}-racket-${{ hashFiles('/share/pkgs/pkgs.rktd') }}
          restore-keys: ${{ runner.os }}-racket
      - name: Linting Python Scripts
        run: pylint scripts/py/* tests/py/*
